// Adhu's Kitchen — dish catalog. Edit names/blurbs freely; id maps to images/<id>.jpg & thumbs/<id>.jpg
// course: starters | mains | desserts   cuisine: south | north | indochinese | global   spice: 0..3
const DISHES = [
{id:"d01",name:"Akkaravadisal",course:"desserts",cuisine:"south",spice:0,date:"2024",fest:"",blurb:"Akkaravadisal - rice and jaggery slow-cooked in milk and ghee, temple-style."},
{id:"d02",name:"Baked Alfredo Pasta",course:"mains",cuisine:"global",spice:1,date:"2024",fest:"",blurb:"Pasta folded through garlicky alfredo, baked under a golden cheese crust."},
{id:"d03",name:"Dragon Fruit Smoothie",course:"desserts",cuisine:"global",spice:0,date:"Mar 2021",fest:"",blurb:"A neon-pink blend of dragon fruit and yogurt — dessert you can drink."},
{id:"d04",name:"Set Dosa with Vada Curry",course:"mains",cuisine:"south",spice:2,date:"May 2021",fest:"",blurb:"Cloud-soft set dosas paired with a spicy, rustic vada curry."},
{id:"d05",name:"Malpua with Rabri",course:"desserts",cuisine:"north",spice:0,date:"Jun 2021",fest:"",blurb:"Crisp-edged festive pancakes drenched in thickened sweet rabri and nuts."},
{id:"d06",name:"Paneer Pasanda",course:"mains",cuisine:"north",spice:2,date:"Jul 2021",fest:"",blurb:"Stuffed paneer parcels bathing in a rich, creamy pasanda gravy with a yogurt drizzle."},
{id:"d07",name:"Caramelised Plantain Fry",course:"desserts",cuisine:"south",spice:0,date:"Aug 2021",fest:"",blurb:"Ripe plantain coins pan-fried in ghee till the edges turn to caramel — Kerala's simplest magic."},
{id:"d08",name:"Chakka Pradhaman",course:"desserts",cuisine:"south",spice:0,date:"May 2023",fest:"",blurb:"Kerala's chakka pradhaman - jackfruit and jaggery payasam served in a brass uruli."},
{id:"d09",name:"Gobi Manchurian",course:"starters",cuisine:"indochinese",spice:3,date:"Dec 2023",fest:"",blurb:"Crisp cauliflower florets wok-tossed in a glossy, garlicky Manchurian sauce."},
{id:"d10",name:"Ven Pongal with Sambar",course:"mains",cuisine:"south",spice:1,date:"Jan 2024",fest:"Pongal",blurb:"Festival-morning ven pongal, ghee-laden and peppery, swimming in hot sambar."},
{id:"d11",name:"Ghee Pongal with Cashews",course:"mains",cuisine:"south",spice:1,date:"Jan 2024",fest:"Pongal",blurb:"Straight from the pot — pongal glistening with ghee, cashews and whole black pepper."},
{id:"d12",name:"Kara Kuzhambu",course:"mains",cuisine:"south",spice:3,date:"Feb 2024",fest:"",blurb:"A fiery, tangy tamarind gravy that demands a mountain of hot rice."},
{id:"d13",name:"Mor Kuzhambu",course:"mains",cuisine:"south",spice:1,date:"Feb 2024",fest:"",blurb:"Gentle buttermilk curry, turmeric-gold, with vegetables bobbing like little boats."},
{id:"d14",name:"Veggie Burger & Fries",course:"mains",cuisine:"global",spice:1,date:"Mar 2024",fest:"",blurb:"Homemade patty, toasted bun, a pile of fries — diner night without leaving home."},
{id:"d15",name:"Methi Malai Paneer",course:"mains",cuisine:"north",spice:1,date:"Mar 2024",fest:"",blurb:"Soft paneer in a silky, cream-mellowed gravy perfumed with fresh methi."},
{id:"d16",name:"Chilli Paneer",course:"starters",cuisine:"indochinese",spice:3,date:"Mar 2024",fest:"",blurb:"Crisp paneer and capsicum lacquered in a glossy, garlicky chilli sauce."},
{id:"d17",name:"Cheese Masala Uttapam",course:"mains",cuisine:"south",spice:2,date:"Apr 2024",fest:"",blurb:"Thick uttapam loaded with masala and a snowfall of cheese — dosa meets pizza."},
{id:"d18",name:"Pineapple Kesari",course:"desserts",cuisine:"south",spice:0,date:"May 2024",fest:"",blurb:"Saffron-bright rava kesari moulded into a dome, sweet with pineapple."},
{id:"d19",name:"Bhindi Masala",course:"mains",cuisine:"north",spice:2,date:"May 2024",fest:"",blurb:"Okra roasted till crisp-edged, folded through onion-tomato masala."},
{id:"d20",name:"Channa Pulao",course:"mains",cuisine:"north",spice:2,date:"Jun 2024",fest:"",blurb:"One-pot pulao studded with brown chickpeas and whole spices."},
{id:"d21",name:"Ennai Kathirikai Kuzhambu",course:"mains",cuisine:"south",spice:3,date:"Jun 2024",fest:"",blurb:"Baby brinjals simmered in a rich sesame-tamarind gravy — grandmother-approved."},
{id:"d22",name:"Crème Caramel",course:"desserts",cuisine:"global",spice:0,date:"Aug 2024",fest:"",blurb:"A trembling crème caramel flipped out in one nervous, triumphant motion."},
{id:"d23",name:"Cheesy Stuffed Mushrooms",course:"starters",cuisine:"global",spice:1,date:"Sep 2024",fest:"",blurb:"Button mushrooms packed with spiced filling and baked under melting cheese."},
{id:"d24",name:"Kozhukattai",course:"desserts",cuisine:"south",spice:0,date:"Sep 2024",fest:"Ganesh Chaturthi",blurb:"Hand-pleated steamed modaks with jaggery-coconut hearts, made for Ganesha."},
{id:"d25",name:"Paneer Butter Masala",course:"mains",cuisine:"north",spice:2,date:"Sep 2024",fest:"",blurb:"The crowd-pleaser: paneer in a buttery tomato-cashew gravy finished with cream and kasuri methi."},
{id:"d26",name:"Beans Paruppu Usili",course:"mains",cuisine:"south",spice:2,date:"Sep 2024",fest:"",blurb:"Steamed lentil crumble tossed with green beans — protein the Tamil way."},
{id:"d27",name:"Masala Vadai",course:"starters",cuisine:"south",spice:3,date:"Sep 2024",fest:"",blurb:"Craggy, crunchy chana-dal fritters with fennel and green chilli — tea-time royalty."},
{id:"d28",name:"Carrot Badam Kheer",course:"desserts",cuisine:"north",spice:0,date:"Oct 2024",fest:"",blurb:"Carrot badam kheer - silky, nutty and chilled till golden."},
{id:"d29",name:"Masala Dosa with Chutney",course:"mains",cuisine:"south",spice:2,date:"Oct 2024",fest:"",blurb:"Crisp golden masala dosa with a spiced potato heart, folded beside chutney."},
{id:"d30",name:"Brownie à la Mode",course:"desserts",cuisine:"global",spice:0,date:"Oct 2024",fest:"",blurb:"Warm fudgy brownie under a scoop of vanilla — the eternal duet."},
{id:"d31",name:"Chilli Mushroom",course:"starters",cuisine:"indochinese",spice:3,date:"Oct 2024",fest:"",blurb:"Wok-charred mushrooms in a sticky chilli glaze with tomato and spring onion."},
{id:"d32",name:"Poha Sheera",course:"desserts",cuisine:"north",spice:0,date:"Oct 2024",fest:"Diwali",blurb:"Soft poha sheera, ghee-toasted and festive gold."},
{id:"d33",name:"Dal Makhani",course:"mains",cuisine:"north",spice:1,date:"Oct 2024",fest:"",blurb:"Black lentils simmered low and slow, swirled with cream — patience you can taste."},
{id:"d34",name:"Lobia Masala",course:"mains",cuisine:"north",spice:2,date:"Nov 2024",fest:"",blurb:"Black-eyed peas in a rustic onion-tomato gravy — humble and hearty."},
{id:"d35",name:"Chocolate Fudge Cake",course:"desserts",cuisine:"global",spice:0,date:"Nov 2024",fest:"",blurb:"Dense, dark and unapologetic — a fudge-frosted chocolate cake cut into generous wedges."},
{id:"d36",name:"Thakkali Rasam",course:"mains",cuisine:"south",spice:3,date:"Jan 2025",fest:"",blurb:"A bold, tangy tomato rasam topped with fresh coriander - soul medicine in a pot."},
{id:"d37",name:"Bisi Bele Bath",course:"mains",cuisine:"south",spice:2,date:"Feb 2025",fest:"",blurb:"Karnataka's beloved hot lentil rice with vegetables and a cashew-ghee finish."},
{id:"d38",name:"Sakkarai Pongal",course:"desserts",cuisine:"south",spice:0,date:"Feb 2025",fest:"",blurb:"Jaggery-sweet sakkarai pongal, slow-stirred with ghee-fried cashews."},
{id:"d39",name:"Pesto Pasta with Veg Balls",course:"mains",cuisine:"global",spice:1,date:"Mar 2025",fest:"",blurb:"Herby green pesto pasta topped with crisp vegetable balls and chilli flakes."},
{id:"d40",name:"Ramen Bowl with Dumplings",course:"mains",cuisine:"indochinese",spice:2,date:"Mar 2025",fest:"",blurb:"Slurpy noodles, pan-crisped dumplings and greens in one steaming bowl."},
{id:"d41",name:"Grilled Paneer Rice Plate with Fries",course:"mains",cuisine:"global",spice:2,date:"May 2025",fest:"",blurb:"Char-grilled paneer over rice and golden fries, eaten with a view."},
{id:"d42",name:"Moong Sprouts Curry",course:"mains",cuisine:"south",spice:2,date:"May 2025",fest:"",blurb:"Sprouted green moong simmered into a homely, nourishing curry."},
{id:"d43",name:"Besan ka Cheela with Chutney",course:"mains",cuisine:"north",spice:2,date:"May 2025",fest:"",blurb:"Savoury gram-flour pancakes crisped with onions, served with fiery chutney."},
{id:"d45",name:"Punjabi Chole Masala",course:"mains",cuisine:"north",spice:2,date:"Jun 2025",fest:"",blurb:"Chickpeas slow-cooked in a punchy Punjabi masala, finished with coriander and ginger."},
{id:"d46",name:"Semiya Payasam",course:"desserts",cuisine:"south",spice:0,date:"Jul 2025",fest:"",blurb:"Roasted vermicelli simmering in sweetened milk — the celebration default."},
{id:"d47",name:"Rose Milk Tres Leches",course:"desserts",cuisine:"global",spice:0,date:"Jul 2025",fest:"",blurb:"Milk-soaked sponge under clouds of cream, strewn with rose petals."},
{id:"d48",name:"One-Pot Rasam Sadham",course:"mains",cuisine:"south",spice:2,date:"Aug 2025",fest:"",blurb:"Comforting one-pot rasam rice, tangy and peppery, topped with coriander."},
{id:"d49",name:"Sabudana Khichdi",course:"mains",cuisine:"north",spice:1,date:"Aug 2025",fest:"",blurb:"Pearly tapioca tossed with potato, peanuts and curry leaves."},
{id:"d50",name:"Chocolate Chip Cookies",course:"desserts",cuisine:"global",spice:0,date:"Aug 2025",fest:"",blurb:"Bakery-style cookies, crackly outside and gooey within."},
{id:"d52",name:"Kerala Veg Stew",course:"mains",cuisine:"south",spice:1,date:"Sep 2025",fest:"",blurb:"Vegetables poached gently in coconut milk with whole spices — appam's soulmate."},
{id:"d53",name:"Chettinad Paal Kozhukattai",course:"mains",cuisine:"south",spice:1,date:"Sep 2025",fest:"",blurb:"Soft rice kozhukattai simmered Chettinad-style in lightly sweetened coconut milk."},
{id:"d54",name:"Dal Tadka",course:"mains",cuisine:"north",spice:2,date:"Sep 2025",fest:"",blurb:"Everyday dal elevated by a crackling ghee tadka."},
{id:"d55",name:"Mushroom Dum Biryani",course:"mains",cuisine:"south",spice:1,date:"Sep 2025",fest:"",blurb:"Slow dum-cooked mushroom biryani, fragrant with whole spices and cashews."},
{id:"d56",name:"Nepali Chukauni with Rice",course:"mains",cuisine:"indochinese",spice:2,date:"Sep 2025",fest:"",blurb:"Nepali chukauni - a tangy yogurt-potato curry - ladled beside steamed rice."},
{id:"d57",name:"Lasooni Palak",course:"mains",cuisine:"north",spice:2,date:"Sep 2025",fest:"",blurb:"Garlic-forward lasooni palak - silky spinach lifted by toasted garlic."},
{id:"d58",name:"Honey Chilli Vegetables",course:"starters",cuisine:"indochinese",spice:3,date:"Oct 2025",fest:"",blurb:"Crispy vegetable batons in a sweet-hot honey chilli glaze with sesame."},
{id:"d59",name:"Rajma Masala",course:"mains",cuisine:"north",spice:1,date:"Oct 2025",fest:"",blurb:"Kidney beans slow-simmered in a rich, buttery tomato masala."},
{id:"d60",name:"Thattai",course:"starters",cuisine:"south",spice:2,date:"Oct 2025",fest:"Diwali",blurb:"Crunchy rice crackers speckled with dal and curry leaves — Diwali's soundtrack."},
{id:"d61",name:"Semiya Upma with Chutney",course:"mains",cuisine:"south",spice:2,date:"Oct 2025",fest:"",blurb:"Vegetable-flecked vermicelli upma with a side of spicy chutney."},
{id:"d62",name:"Chole Bhature",course:"mains",cuisine:"north",spice:2,date:"Oct 2025",fest:"",blurb:"Puffed-up bhature and dark, spicy chole with onion rings — the Delhi classic."},
{id:"d63",name:"Vanilla Sponge Cake",course:"desserts",cuisine:"global",spice:0,date:"Nov 2025",fest:"",blurb:"A cloud-soft vanilla sponge under smooth cream."},
{id:"d64",name:"Swedish Kladdkaka",course:"desserts",cuisine:"global",spice:0,date:"Dec 2025",fest:"",blurb:"Swedish kladdkaka - a sticky, fudgy chocolate cake with a crackly top."},
{id:"d65",name:"Eggplant Parmigiana",course:"mains",cuisine:"global",spice:1,date:"Dec 2025",fest:"",blurb:"Layers of eggplant, tomato sauce and cheese baked till bubbling - Italian comfort."},
{id:"d66",name:"Pesarattu with Sambar",course:"mains",cuisine:"south",spice:2,date:"Dec 2025",fest:"",blurb:"Green-gram dosa from Andhra, folded beside hot sambar."},
{id:"d67",name:"Lemon Blueberry Cake",course:"desserts",cuisine:"global",spice:0,date:"Dec 2025",fest:"",blurb:"Buttery lemon cake with a jammy blueberry layer and golden crumb."},
{id:"d68",name:"Pepper Rasam",course:"mains",cuisine:"south",spice:3,date:"Feb 2026",fest:"",blurb:"A sharp, warming pepper rasam - sinus-clearing soul medicine."},
{id:"d69",name:"Bun Dosai with Kara Chutney",course:"mains",cuisine:"south",spice:2,date:"Feb 2026",fest:"",blurb:"Fluffy bun dosai with a swipe of fiery kara chutney."},
{id:"d70",name:"Vegetable Au Gratin",course:"mains",cuisine:"global",spice:1,date:"Mar 2026",fest:"",blurb:"A glass dish of vegetables in white sauce under a molten, golden cheese lid."},
{id:"d71",name:"Parotta with Salna",course:"mains",cuisine:"south",spice:3,date:"Mar 2026",fest:"",blurb:"Flaky street-style parotta swimming in pepper-hot salna."},
{id:"d72",name:"Cauliflower Kati Rolls",course:"mains",cuisine:"north",spice:2,date:"Apr 2026",fest:"",blurb:"Spiced cauliflower and crunchy veg wrapped tight in soft rotis."},
{id:"d73",name:"Palak Paneer",course:"mains",cuisine:"north",spice:1,date:"Apr 2026",fest:"",blurb:"Deep-green saag slow-cooked with paneer and a swirl of cream."},
{id:"d74",name:"South Indian Mini Thali",course:"mains",cuisine:"south",spice:2,date:"Apr 2026",fest:"",blurb:"A little feast: rice, kurma, chutney and podi all at once."},
{id:"d76",name:"Thai Red Curry with Rice Noodles",course:"mains",cuisine:"indochinese",spice:2,date:"Apr 2026",fest:"",blurb:"Rice noodles coiled into a fragrant, coconut-rich Thai red curry."},
{id:"d77",name:"Roadside Kaalan",course:"starters",cuisine:"south",spice:3,date:"May 2026",fest:"",blurb:"Roadside-style kaalan - mushrooms smashed on the hot tawa with bold street masala."},
{id:"d78",name:"Kadai Paneer",course:"mains",cuisine:"north",spice:2,date:"May 2026",fest:"",blurb:"Paneer and capsicum tossed in freshly-pounded kadai masala."},
{id:"d79",name:"Lasagna",course:"mains",cuisine:"global",spice:1,date:"Jun 2026",fest:"",blurb:"Layer upon layer of pasta, ragu and cheese, baked till burnished."},
{id:"d80",name:"Veg Lahori",course:"mains",cuisine:"north",spice:2,date:"Jul 2026",fest:"",blurb:"Vegetables in a rich Lahori-style gravy, finished with fresh herbs."},
{id:"d81",name:"Hara Bhara Kabab",course:"starters",cuisine:"north",spice:1,date:"Jul 2026",fest:"",blurb:"Spinach-and-pea kababs baked golden, each crowned with a cashew."},
{id:"d82",name:"Creamy White Sauce Pasta",course:"mains",cuisine:"global",spice:1,date:"Oct 2023",fest:"",blurb:"Spaghetti and vegetables folded through a garlicky white sauce."},
{id:"d84",name:"Mini Rava Idli with Sambar",course:"mains",cuisine:"south",spice:1,date:"Nov 2023",fest:"",blurb:"Mini rava idlis, soft and tempered, under a generous ladle of sambar."},
{id:"d85",name:"Aloo Subzi",course:"mains",cuisine:"north",spice:3,date:"Dec 2023",fest:"",blurb:"Homely aloo subzi - potatoes in a comforting spiced gravy."},
{id:"d86",name:"Ulundhu Sadam",course:"mains",cuisine:"south",spice:2,date:"Jul 2026",fest:"",blurb:"Nutty ulundhu sadam - urad dal rice, earthy, homely and strengthening."},
{id:"d88",name:"Veg Seekh Kabab with Mint Chutney",course:"starters",cuisine:"north",spice:2,date:"May 2026",fest:"",blurb:"Char-grilled veg seekh kababs with a vivid mint chutney for dunking."},
{id:"d89",name:"Creamy Cauliflower Curry",course:"mains",cuisine:"north",spice:2,date:"May 2026",fest:"",blurb:"Cauliflower florets simmered soft in a gently spiced, creamy gravy."},
{id:"d92",name:"Thai Green Curry with Rice",course:"mains",cuisine:"indochinese",spice:2,date:"Jul 2026",fest:"",blurb:"Fragrant homemade green curry ladled over basmati, showered with spring onion."},
{id:"d93",name:"Home-made Paneer Tikka Pizza",course:"mains",cuisine:"global",spice:2,date:"Jul 2026",fest:"",blurb:"Hand-stretched dough, smoky paneer tikka and olives under blistered cheese — home-made from base to crust."},
{id:"d94",name:"Vendakkai Sambar",course:"mains",cuisine:"south",spice:2,date:"Jul 2026",fest:"",blurb:"Okra simmered into a rustic, tangy sambar with fresh coriander."},
{id:"d95",name:"Rava Upma with Sambar",course:"mains",cuisine:"south",spice:2,date:"Jul 2026",fest:"",blurb:"A steaming dome of vegetable-studded rava upma, moated by hot sambar."}
];

// ---- site contact config: fill in your WhatsApp number with country code (e.g. "46701234567") to enable WhatsApp buttons; otherwise email is used ----
const SITE = { whatsapp: "919940222977", email: "claude.jth@ju.se" };

// ---- your proudest dishes, shown in the Signature strip (edit freely) ----
const SIGNATURES = ["d71","d33","d49","d78","d65","d64","d01"];

// ---- Tamil dish names for the தமிழ் toggle ----
const TA_NAMES = {
d01:"அக்கார வடிசல்",d02:"பேக்டு அல்ஃப்ரெடோ பாஸ்தா",d03:"டிராகன் பழ ஸ்மூத்தி",d04:"செட் தோசை & வடை கறி",
d05:"மால்புவா & ரப்டி",d06:"பன்னீர் பசந்தா",d07:"நேந்திரம் பழ வறுவல்",d08:"சக்க பிரதமன்",
d09:"கோபி மஞ்சூரியன்",d10:"வெண் பொங்கல் & சாம்பார்",d11:"நெய் பொங்கல்",d12:"கார குழம்பு",
d13:"மோர் குழம்பு",d14:"வெஜ் பர்கர் & ஃப்ரைஸ்",d15:"மேத்தி மலாய் பன்னீர்",d16:"சில்லி பன்னீர்",
d17:"சீஸ் மசாலா ஊத்தாப்பம்",d18:"அன்னாசி கேசரி",d19:"வெண்டைக்காய் மசாலா",d20:"கொண்டைக்கடலை புலாவ்",
d21:"எண்ணெய் கத்திரிக்காய் குழம்பு",d22:"கிரீம் கேரமல்",d23:"சீஸ் ஸ்டஃப்டு காளான்",d24:"கொழுக்கட்டை",
d25:"பன்னீர் பட்டர் மசாலா",d26:"பீன்ஸ் பருப்பு உசிலி",d27:"மசால் வடை",d28:"கேரட் பாதாம் கீர்",
d29:"மசாலா தோசை & சட்னி",d30:"பிரௌனி & ஐஸ்கிரீம்",d31:"சில்லி காளான்",d32:"அவல் ஷீரா",
d33:"தால் மக்கனி",d34:"காராமணி மசாலா",d35:"சாக்லேட் கேக்",d36:"தக்காளி ரசம்",
d37:"பிசிபேளாபாத்",d38:"சக்கரை பொங்கல்",d39:"பெஸ்டோ பாஸ்தா & வெஜ் பால்ஸ்",d40:"ராமென் & மோமோ பவுல்",
d41:"கிரில்டு பன்னீர் & ஃப்ரைஸ்",d42:"முளைப்பயறு கறி",d43:"கடலைமாவு சீலா & சட்னி",d45:"பஞ்சாபி சோலே மசாலா",
d46:"சேமியா பாயசம்",d47:"ரோஸ் மில்க் ட்ரெஸ் லெச்சஸ்",d48:"ஒன்-பாட் ரசம் சாதம்",d49:"ஜவ்வரிசி கிச்சடி",
d50:"சாக்லேட் சிப் குக்கீஸ்",d52:"கேரள இஸ்து",d53:"செட்டிநாடு பால் கொழுக்கட்டை",
d54:"தால் தட்கா",d55:"காளான் தம் பிரியாணி",d56:"நேபாளி சுகௌனி & சாதம்",d57:"லசூனி பாலக்",
d58:"ஹனி சில்லி வெஜிடபிள்ஸ்",d59:"ராஜ்மா மசாலா",d60:"தட்டை",d61:"சேமியா உப்புமா & சட்னி",
d62:"சோலே பட்டூரா",d63:"வெண்ணிலா ஸ்பான்ஜ் கேக்",d64:"கிளாட்காக்கா",d65:"கத்திரிக்காய் பார்மிஜானா",
d66:"பெசரட்டு & சாம்பார்",d67:"எலுமிச்சை புளுபெர்ரி கேக்",d68:"மிளகு ரசம்",d69:"பன் தோசை & கார சட்னி",
d70:"வெஜிடபிள் கிரேட்டின்",d71:"பரோட்டா & சால்னா",d72:"காலிஃப்ளவர் காத்தி ரோல்",d73:"பாலக் பன்னீர்",
d74:"மினி விருந்து தட்டு",d76:"தாய் ரெட் கறி நூடுல்ஸ்",d77:"ரோட்டுக்கடை காளான்",
d78:"கடாய் பன்னீர்",d79:"லசான்யா",d80:"வெஜ் லாஹோரி",d81:"ஹரா பரா கபாப்",
d82:"வைட் சாஸ் பாஸ்தா",d84:"மினி ரவை இட்லி & சாம்பார்",d85:"உருளை கிழங்கு கறி",
d86:"உளுந்து சாதம்",d88:"வெஜ் சீக் கபாப் & புதினா சட்னி",d89:"காலிஃப்ளவர் கிரீமி கறி",
d92:"தாய் கிரீன் கறி & சாதம்",d93:"பன்னீர் டிக்கா பிட்சா",
d94:"வெண்டைக்காய் சாம்பார்",
d95:"ரவை உப்புமா & சாம்பார்"
};
